# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spec-assist}
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan L. Walls"]
  s.date = %q{2010-11-28}
  s.description = %q{A gem with helper methods for use with rspec tests}
  s.email = %q{nathan@rexluther.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION.yml",
    "lib/spec_assist.rb",
    "pkg/spec-assist-0.5.1.gem",
    "spec-assist.gemspec",
    "test/spec_assist_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/base10/spec-assist}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Initial commit}
  s.test_files = [
    "test/spec_assist_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

